import type { Assert } from 'ts-runtime-checks';

interface EnvData {
  EXPO_PUBLIC_CurrentData: string;
}

/**
 * This function implementation is generated by ts-runtime checks,
 * is not meant to be edited manually
 */
function validateEnv(a: Assert<EnvData>) {
  if (typeof a !== 'object' || a === null) {
    throw new Error('Expected a to be EnvData');
  }
  if (typeof a.EXPO_PUBLIC_CurrentData !== 'string') {
    throw new Error('Expected a.EXPO_CurrentData to be a string');
  }
  return a as EnvData;
}

const envData = process.env;
export const ENV = validateEnv(envData as any);
